Sub AsignacionTransito()
Sheets("Tránsito").TDPA1.Text = Sheets("Tránsito").Cells(4, 21)
Sheets("Tránsito").FDS1.Text = Sheets("Tránsito").Cells(5, 21)
Sheets("Tránsito").FDC1.Text = Sheets("Tránsito").Cells(6, 21)
Sheets("Tránsito").Tasa1.Text = Sheets("Tránsito").Cells(7, 21)
Sheets("Tránsito").años1.Text = Sheets("Tránsito").Cells(8, 21)
Sheets("Tránsito").vehiculoA.Text = Sheets("Tránsito").Cells(9, 21)
Sheets("Tránsito").VehiculoB2.Text = Sheets("Tránsito").Cells(10, 21)
Sheets("Tránsito").VehiculoB3.Text = Sheets("Tránsito").Cells(11, 21)
Sheets("Tránsito").VehiculoC2.Text = Sheets("Tránsito").Cells(12, 21)
Sheets("Tránsito").vehiculoC3.Text = Sheets("Tránsito").Cells(13, 21)
Sheets("Tránsito").VehiculoT3S2.Text = Sheets("Tránsito").Cells(14, 21)
Sheets("Tránsito").VehiculoT3S3.Text = Sheets("Tránsito").Cells(15, 21)
Sheets("Tránsito").VehiculoT3S2R4.Text = Sheets("Tránsito").Cells(16, 21)
Sheets("Tránsito").otros.Text = Sheets("Tránsito").Cells(17, 21)
End Sub