/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vista.Dialogos;

import Clases.CargarClases;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aldoj
 */
public class VerTablas extends javax.swing.JDialog {

    DefaultTableModel dtm;
    CargarClases cc;

    public VerTablas(java.awt.Frame parent, boolean modal, CargarClases cc) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.cc = cc;

    }

    public void setDatos(String[] columnas) {
        dtm.addColumn("Numero");
        for (String columna : columnas) {
            dtm.addColumn(columna);
        }

    }

    public void addFila(Vector fila) {
        Vector fin = new Vector();
        fin.add(0, 1 + dtm.getRowCount());
        for (var r : fila.toArray()) {
            fin.add(r);
        }

        dtm.addRow(fin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        seleccion = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("Selecciona Una Tabla:");

        seleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opcion", "General", "Respuesta eje simple", "Respuesta eje dual", "Respuesta eje tandem", "Respuesta eje tridem", "Repeticiones Admisibles por eje", "Espectro Repeticiones Esperadas", "Espectro de Daño", "Espectro de Daño total", "Espectro de Daño acomulado", "Vida util" }));

        jButton1.setText("Ver Tabla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int index = seleccion.getSelectedIndex()-1 ;
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una opcion valida");
        } else {
            dtm = new DefaultTableModel();
            tabla.setModel(dtm);
            switch (index) {
                case 0:
                    setDatos(this.cc.columnasLarguilloNormal);
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.data[i].getVector());
                    }
                    break;
                case 1:
                case 2:
                case 3:
                case 4:
                    setDatos(this.cc.columnasRespuestasEje);
                    for (int i = 0; i < 100; i++) {

                        if (index == 1) {
                            addFila(this.cc.simpleRespuesta[i].getVector());
                        }
                        if (index == 2) {
                            addFila(this.cc.dualRespuesta[i].getVector());
                        }
                        if (index == 3) {
                            addFila(this.cc.tandemRespuesta[i].getVector());
                        }
                        if (index == 4) {
                            addFila(this.cc.tridemRespuesta[i].getVector());
                        }
                    }
                    break;

                case 5://deformacion y fatiga 1

                    setDatos(this.cc.columnasRespuestasEje());
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.nre[i].getVector());
                    }

                    break;
                case 6://espectros de repeticiones esperadas
                    setDatos(this.cc.colEspectroRepeticionesEsperadas);
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.ere[i].getVector());
                    }
                    break;
                case 7://fatiga y deformacion 2
                    setDatos(this.cc.columnasRespuestasEje());
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.ed[i].getVector());
                    }
                    break;
                case 8://deformacion todos
                    setDatos(this.cc.colsEspectroTotal);
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.et[i].getVector());
                    }
                    break;
                case 9://espectro de daño acomulado
                    setDatos("Simple Def, Dual Def, Tandem Def, TRIDEM def, TODOS def,Simple fat, Dual fat, Tandem fat, TRIDEM fat, TODOS fat".split(","));
                    for (int i = 0; i < 100; i++) {
                        addFila(this.cc.eda[i].getVector());
                    }
                    break;
                    case 10://espectro de daño acomulado
                    setDatos("Simple Def, Dual Def, Tandem Def, TRIDEM def, TODOS def,Simple fat, Dual fat, Tandem fat, TRIDEM fat, TODOS fat".split(","));
                    for (int i = 0; i < 3; i++) {
                        addFila(this.cc.vi[i].getVector());
                    }
                    break;

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> seleccion;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
