/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Clases.CargarClases;
import Clases.TransitoEstatico;
import controladores.CAnalisis;
import controladores.CTransito;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Vector;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import vista.Dialogos.AgregarCapa;
import vista.Dialogos.AgregarValor;
import vista.Dialogos.Continuar;
import vista.Dialogos.Grafica;
import vista.Dialogos.TransitoDialogo;
import vista.Dialogos.VerLarguillo;

/**
 *
 * @author aldoj
 */
public class VentanaFinal extends javax.swing.JFrame {

    private DefaultTableModel dtm;
    private CargarClases cc;
    private CAnalisis ca;
    private VerLarguillo vl;
    private CTransito ct;
    private ButtonGroup grupo1;

    public VentanaFinal(CargarClases cc) {
        super();
        initComponents();
        this.setLocationRelativeTo(null);

        this.cc = cc;
        ca = new CAnalisis(this.cc);
        dtm = new DefaultTableModel();

        dtm = (DefaultTableModel) tabla.getModel();
        tabla.setModel(dtm);

        grupo1 = new ButtonGroup();
        grupo1.add(probabilistico);
        grupo1.add(espectral);
        /*
        agregarCapa.addActionListener((var e) -> {
            AgregarCapa ac = new AgregarCapa(null, true);
            ac.setVisible(true);
            if (ac.getEstado()) {
                var valor = new Vector(5);
                valor.add(dtm.getRowCount() + 1);
                valor.add(ac.getNombreCapa());
                valor.add(ac.getEspesorCapa());
                valor.add(ac.getModulo());
                valor.add(ac.getCoeficiente());
                dtm.addRow(valor);
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tabla1 = new javax.swing.JButton();
        respuestaSimple = new javax.swing.JButton();
        respuestaDual = new javax.swing.JButton();
        respuestaTandem = new javax.swing.JButton();
        respuestaTridem = new javax.swing.JButton();
        deformacionFatiga1 = new javax.swing.JButton();
        espectrosRepeticiones = new javax.swing.JButton();
        deformacionFatiga2 = new javax.swing.JButton();
        deformacionFatigaTodos = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        espectral = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        vidaFatiga = new javax.swing.JTextField();
        vidaDeformacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        confianza = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        botonPresion = new javax.swing.JButton();
        botonPoisson = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        tipoCarga = new javax.swing.JComboBox<>();
        probabilistico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Larguillo");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        tabla1.setBackground(new java.awt.Color(204, 255, 204));
        tabla1.setText("Tabla 1");
        tabla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabla1ActionPerformed(evt);
            }
        });

        respuestaSimple.setBackground(new java.awt.Color(204, 255, 204));
        respuestaSimple.setText("Respuesta Simple");
        respuestaSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaSimpleActionPerformed(evt);
            }
        });

        respuestaDual.setBackground(new java.awt.Color(204, 255, 204));
        respuestaDual.setText("Respuesta Dual");
        respuestaDual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaDualActionPerformed(evt);
            }
        });

        respuestaTandem.setBackground(new java.awt.Color(204, 255, 204));
        respuestaTandem.setText("Respuesta Tandem");
        respuestaTandem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaTandemActionPerformed(evt);
            }
        });

        respuestaTridem.setBackground(new java.awt.Color(204, 255, 204));
        respuestaTridem.setText("Respuesta Tridem");
        respuestaTridem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaTridemActionPerformed(evt);
            }
        });

        deformacionFatiga1.setBackground(new java.awt.Color(204, 255, 204));
        deformacionFatiga1.setText("Deformacion/Fatiga 1");
        deformacionFatiga1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deformacionFatiga1ActionPerformed(evt);
            }
        });

        espectrosRepeticiones.setBackground(new java.awt.Color(204, 255, 204));
        espectrosRepeticiones.setText("Espectro Repeticiones");
        espectrosRepeticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espectrosRepeticionesActionPerformed(evt);
            }
        });

        deformacionFatiga2.setBackground(new java.awt.Color(204, 255, 204));
        deformacionFatiga2.setText("Deformacion/Fatiga 2");
        deformacionFatiga2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deformacionFatiga2ActionPerformed(evt);
            }
        });

        deformacionFatigaTodos.setBackground(new java.awt.Color(204, 255, 204));
        deformacionFatigaTodos.setText("Deformacion/Fatiga Todos");
        deformacionFatigaTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deformacionFatigaTodosActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setText("Deformacion Fatiga Final");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Ver Graficas");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabla1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(respuestaSimple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(respuestaDual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(respuestaTandem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(respuestaTridem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deformacionFatiga1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(espectrosRepeticiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deformacionFatiga2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deformacionFatigaTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabla1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuestaSimple)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuestaDual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuestaTandem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(respuestaTridem)
                .addGap(18, 18, 18)
                .addComponent(deformacionFatiga1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(espectrosRepeticiones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deformacionFatiga2)
                .addGap(18, 18, 18)
                .addComponent(deformacionFatigaTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("Cargar Transito");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        espectral.setSelected(true);
        espectral.setText("Analisis Espectral");
        espectral.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 1, new java.awt.Color(255, 255, 255)));

        jLabel13.setBackground(new java.awt.Color(204, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Deformacion permanente");
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setOpaque(true);

        jLabel14.setBackground(new java.awt.Color(204, 204, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Vida por fatiga (años):");
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setOpaque(true);

        jLabel15.setBackground(new java.awt.Color(204, 204, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Vida por deformacion (años):");
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setOpaque(true);

        vidaFatiga.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vidaFatiga.setText("10.2");
        vidaFatiga.setEnabled(false);

        vidaDeformacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        vidaDeformacion.setText("5.4");
        vidaDeformacion.setEnabled(false);

        jLabel4.setBackground(new java.awt.Color(204, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Confiabilidad:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);

        confianza.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confianza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "60%", "65%", "70%", "75%", "80%", "85%", "90%", "95%" }));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Estructura del pavimento");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "carpeta", "10", "3500", "20"},
                {"2", "base", "40", "400", "20"},
                {"3", "subbase", "", "100", "20"}
            },
            new String [] {
                "Numero de capas", "Nombre capa", "Espesor (cm)", "Modulo (MPa)", "Coe de var %"
            }
        ));
        tabla.setToolTipText("");
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jScrollPane2.setViewportView(tabla);

        botonPresion.setText("Modificar presion estandar");
        botonPresion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPresionActionPerformed(evt);
            }
        });

        botonPoisson.setText("Modificar Poisson");
        botonPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPoissonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Iniciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        mensaje.setForeground(new java.awt.Color(255, 102, 102));
        mensaje.setText("Transito no cargado.");

        tipoCarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Legal", "Ligera Sobre Carga", "Alta Sobre Carga", "Muy Alta Sobre Carga" }));

        probabilistico.setSelected(true);
        probabilistico.setText("Analisis Probabilistico");
        probabilistico.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 1, new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vidaDeformacion)
                            .addComponent(vidaFatiga, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonPoisson, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoCarga, javax.swing.GroupLayout.Alignment.TRAILING, 0, 251, Short.MAX_VALUE)
                                .addComponent(botonPresion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(confianza, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(probabilistico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espectral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vidaFatiga, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vidaDeformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(espectral)
                        .addGap(2, 2, 2)
                        .addComponent(probabilistico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confianza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonPresion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonPoisson)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(5, 5, 5))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPresionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPresionActionPerformed
        AgregarValor av = new AgregarValor(null, true, "Presion inflado");
        av.setValor(ca.getPresion());
        av.setVisible(true);
        if (av.isEstado()) {
            ca.setPresion(av.getValor());
        }
    }//GEN-LAST:event_botonPresionActionPerformed

    private void botonPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPoissonActionPerformed
        AgregarValor av = new AgregarValor(null, true, "Poisson");
        av.setValor(ca.getPoisson());
        av.setVisible(true);
        if (av.isEstado()) {
            ca.setPoisson(av.getValor());
        }
    }//GEN-LAST:event_botonPoissonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (dtm.getRowCount() < 1 || TransitoEstatico.activado == 0) {
            JOptionPane.showMessageDialog(null, "La tabla debe tener una \ncapa por lo menos");
        } else {
            ca.CargarTabla(dtm);
            ca.setCTransito(ct);
            if (probabilistico.isSelected()) {
                ca.IniciarAnalisisEspectral(tipoCarga.getModel().getSelectedItem() + "");
            }
            if (espectral.isSelected()) {
                ca.IniciarAnalisisProbabilistico(tipoEje, confiabilidad);
            }

            
            cc = ca.getClases();
            this.vidaDeformacion.setText(ca.getFidef());
            this.vidaFatiga.setText(ca.getVifat());

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        TransitoDialogo td = new TransitoDialogo(this, true);
        td.setVisible(true);
        if (TransitoEstatico.activado != 0) {
            JOptionPane.showMessageDialog(null, "Transito Cargado", "Listo", JOptionPane.PLAIN_MESSAGE);
            ct = td.getCTransito();
            mensaje.setText("Transito cargado");
            mensaje.setForeground(Color.black);
        } else {
            mensaje.setText("Transito no cargado");
            mensaje.setForeground(Color.red);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tabla1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabla1ActionPerformed
        abrirLarguillo(0);
    }//GEN-LAST:event_tabla1ActionPerformed

    private void respuestaSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaSimpleActionPerformed
        abrirLarguillo(1);
    }//GEN-LAST:event_respuestaSimpleActionPerformed

    private void respuestaDualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaDualActionPerformed
        abrirLarguillo(2);
    }//GEN-LAST:event_respuestaDualActionPerformed

    private void respuestaTandemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaTandemActionPerformed
        abrirLarguillo(3);
    }//GEN-LAST:event_respuestaTandemActionPerformed

    private void respuestaTridemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaTridemActionPerformed
        abrirLarguillo(4);
    }//GEN-LAST:event_respuestaTridemActionPerformed

    private void deformacionFatiga1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deformacionFatiga1ActionPerformed
        abrirLarguillo(5);
    }//GEN-LAST:event_deformacionFatiga1ActionPerformed

    private void espectrosRepeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espectrosRepeticionesActionPerformed
        abrirLarguillo(6);
    }//GEN-LAST:event_espectrosRepeticionesActionPerformed

    private void deformacionFatiga2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deformacionFatiga2ActionPerformed
        abrirLarguillo(7);
    }//GEN-LAST:event_deformacionFatiga2ActionPerformed

    private void deformacionFatigaTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deformacionFatigaTodosActionPerformed
        abrirLarguillo(8);
    }//GEN-LAST:event_deformacionFatigaTodosActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        abrirLarguillo(9);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Grafica gr = new Grafica(this, false);
        gr.setLargilloNormal(this.cc.data);
        gr.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void abrirLarguillo(int opcion) {
        vl = new VerLarguillo(null, false);

        switch (opcion) {
            case 0:
                vl.setDatos(this.cc.columnasLarguilloNormal);
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.data[i].getVector());
                }
                break;
            case 1:
            case 2:
            case 3:
            case 4:
                vl.setDatos(this.cc.columnasRespuestasEje);
                for (int i = 0; i < 100; i++) {

                    if (opcion == 1) {
                        vl.addFila(this.cc.simpleRespuesta[i].getVector());
                    }
                    if (opcion == 2) {
                        vl.addFila(this.cc.dualRespuesta[i].getVector());
                    }
                    if (opcion == 3) {
                        vl.addFila(this.cc.tandemRespuesta[i].getVector());
                    }
                    if (opcion == 4) {
                        vl.addFila(this.cc.tridemRespuesta[i].getVector());
                    }
                }
                break;

            case 5://deformacion y fatiga 1

                vl.setDatos(this.cc.columnasRespuestasEje());
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.nre[i].getVector());
                }

                break;
            case 6://espectros de repeticiones esperadas
                vl.setDatos(this.cc.colEspectroRepeticionesEsperadas);
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.ere[i].getVector());
                }
                break;
            case 7://fatiga y deformacion 2
                vl.setDatos(this.cc.columnasRespuestasEje());
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.ed[i].getVector());
                }
                break;
            case 8://deformacion todos
                vl.setDatos(this.cc.colsEspectroTotal);
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.et[i].getVector());
                }
                break;
            case 9://espectro de daño acomulado
                vl.setDatos("Simple Def, Dual Def, Tandem Def, TRIDEM def, TODOS def,Simple fat, Dual fat, Tandem fat, TRIDEM fat, TODOS fat".split(","));
                for (int i = 0; i < 100; i++) {
                    vl.addFila(this.cc.eda[i].getVector());
                }
                break;

        }
        vl.setNoEditable();
        vl.setVisible(true);

    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFinal(new CargarClases()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPoisson;
    private javax.swing.JButton botonPresion;
    private javax.swing.JComboBox<String> confianza;
    private javax.swing.JButton deformacionFatiga1;
    private javax.swing.JButton deformacionFatiga2;
    private javax.swing.JButton deformacionFatigaTodos;
    private javax.swing.JRadioButton espectral;
    private javax.swing.JButton espectrosRepeticiones;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JRadioButton probabilistico;
    private javax.swing.JButton respuestaDual;
    private javax.swing.JButton respuestaSimple;
    private javax.swing.JButton respuestaTandem;
    private javax.swing.JButton respuestaTridem;
    private javax.swing.JTable tabla;
    private javax.swing.JButton tabla1;
    private javax.swing.JComboBox<String> tipoCarga;
    private javax.swing.JTextField vidaDeformacion;
    private javax.swing.JTextField vidaFatiga;
    // End of variables declaration//GEN-END:variables

}
